apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: demo

  # ðŸ”½ REQUIRED by backend Deployment
  MYSQL_USER: root
  MYSQL_PASSWORD: rootpass
